language: node_js
node_js:
  - '8'

cache:
  npm: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - npm set progress=false
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run build:css
  - npm run test:all
  - npm run build

after_success:
  - npm run coverage

branches:
  only:
    - master
